### ISSUE TITLE
onNodeDoubleClick not work

### ISSUE THREAD

**Issue by PittYao** [Alex-Li2018/neo4j-d3-graph#1]
hey bro 
I added a method onNodeDoubleClick in html，but onMenuNodeClick is work
but not console 
do you know how to solve it
![image](https://user-images.githubusercontent.com/26101917/167240948-6fc36222-09a6-4ca5-a75c-0a1745ee31ec.png)

**Comment by Alex-Li2018** [comment]
我检查下是不是有bug

**Comment by Alex-Li2018** [comment]
resolved 已经解决，请再试试，欢迎star。
