### ISSUE TITLE
neo4jDataUrl load  json  not  work

### ISSUE THREAD

**Issue by cor0ps** [Alex-Li2018/neo4j-d3-graph#3]
I  use  neo4jDataUrl  load  json  but    the  nodes  is  none

        loadNeo4jDataFromUrl(neo4jDataUrl) {
            const self = this;
            this.nodes = [];
            this.relationships = [];
            console.log(neo4jDataUrl);
            d3.json(neo4jDataUrl, (error, data) => {
                self.updateWithNeo4jData(data);
            });
        }

why  here  use  d3.json load  neo4jData?

**Comment by Alex-Li2018** [comment]
this is a bug! ohhhhhh

**Comment by Alex-Li2018** [comment]
If you don't use this way, no problem, you can use `fetch` `Ajax`. d3.json() is a method of get data. In summary，d3.json() don't need to import other libraries.it Can reduce library size.

**Comment by Alex-Li2018** [comment]
resolve
