### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by johncolezhang** [Alex-Li2018/neo4j-d3-graph#4]
Tried:
```
npm install
npm start
```

But can not start the server.

**Comment by Alex-Li2018** [comment]
if you want to see the effect，you can use like this:
```js
<link href="./dist/neo4jd3.css"></link>
<script src="https://d3js.org/d3.v7.min.js"></script>

<div 
    id="neo4j-d3" 
    ref="neo4j-d3" 
>
</div>
```

if you want to commit code, Please fork this project.

if you want to privatized deployment, you can use like this:

```bash
npm install

## modify code 

## package project development

npm run build:dev

or  package project prod

npm run build:pro
```

**Comment by Alex-Li2018** [comment]
You want to have a variety of experiences in graph visualization， you can move to [https://github.com/Alex-Li2018/graph-explorer](url).
