### ISSUE TITLE
How to use icons and images for the nodes

### ISSUE THREAD

**Issue by jefflink** [Alex-Li2018/neo4j-d3-graph#5]
Hi,

Thanks for the great project! Sometimes visual (e.g. icon/image) provides a better view for the graph. How can I include icons / images in the nodes? or perhaps combination of Icons/Image with text?

**Comment by Alex-Li2018** [comment]
only support icons not support images, options like this:

1. import font static
2. set options
```js
iconMap: {
    'rich-text': 'e65f',
}
```

**Comment by Alex-Li2018** [comment]
You want to have a variety of experiences in graph visualization， you can move to [https://github.com/Alex-Li2018/graph-explorer](https://github.com/Alex-Li2018/neo4j-d3-graph/issues/url).
