### ISSUE TITLE
图例功能没有显示？

### ISSUE THREAD

**Issue by lionliujia** [Alex-Li2018/neo4j-d3-graph#7]
初始化代码里：
onGetLegend(data) {
                console.log(data)
            },
似乎没有绘图的代码？

**Comment by Alex-Li2018** [comment]
没有需要自己绘制

**Comment by Alex-Li2018** [comment]
只是给了图例的数据获取回调函数

**Comment by Alex-Li2018** [comment]
没有其他问题我把issue关闭了
